/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as PowerImport } from './routes/power'
import { Route as NetworkImport } from './routes/network'
import { Route as FloorplanImport } from './routes/floorplan'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as TemplatesIndexImport } from './routes/templates/index'
import { Route as NodesIndexImport } from './routes/nodes/index'
import { Route as ImagesIndexImport } from './routes/images/index'
import { Route as TemplatesTemplateImport } from './routes/templates/$template'
import { Route as RackRackImport } from './routes/rack/$rack'
import { Route as NodesNodeImport } from './routes/nodes/$node'
import { Route as ImagesImageImport } from './routes/images/$image'
import { Route as AddTemplateImport } from './routes/add/template'
import { Route as AddNodeImport } from './routes/add/node'
import { Route as AddImageImport } from './routes/add/image'
import { Route as AccountLoginImport } from './routes/account/login'
import { Route as AccountCreateImport } from './routes/account/create'
import { Route as GroupsNodesIndexImport } from './routes/groups/nodes/index'
import { Route as GroupsNodesGroupImport } from './routes/groups/nodes/$group'

// Create/Update Routes

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PowerRoute = PowerImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRoute,
} as any)

const NetworkRoute = NetworkImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRoute,
} as any)

const FloorplanRoute = FloorplanImport.update({
  id: '/floorplan',
  path: '/floorplan',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesIndexRoute = TemplatesIndexImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRoute,
} as any)

const NodesIndexRoute = NodesIndexImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRoute,
} as any)

const ImagesIndexRoute = ImagesIndexImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesTemplateRoute = TemplatesTemplateImport.update({
  id: '/templates/$template',
  path: '/templates/$template',
  getParentRoute: () => rootRoute,
} as any)

const RackRackRoute = RackRackImport.update({
  id: '/rack/$rack',
  path: '/rack/$rack',
  getParentRoute: () => rootRoute,
} as any)

const NodesNodeRoute = NodesNodeImport.update({
  id: '/nodes/$node',
  path: '/nodes/$node',
  getParentRoute: () => rootRoute,
} as any)

const ImagesImageRoute = ImagesImageImport.update({
  id: '/images/$image',
  path: '/images/$image',
  getParentRoute: () => rootRoute,
} as any)

const AddTemplateRoute = AddTemplateImport.update({
  id: '/add/template',
  path: '/add/template',
  getParentRoute: () => rootRoute,
} as any)

const AddNodeRoute = AddNodeImport.update({
  id: '/add/node',
  path: '/add/node',
  getParentRoute: () => rootRoute,
} as any)

const AddImageRoute = AddImageImport.update({
  id: '/add/image',
  path: '/add/image',
  getParentRoute: () => rootRoute,
} as any)

const AccountLoginRoute = AccountLoginImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRoute,
} as any)

const AccountCreateRoute = AccountCreateImport.update({
  id: '/account/create',
  path: '/account/create',
  getParentRoute: () => rootRoute,
} as any)

const GroupsNodesIndexRoute = GroupsNodesIndexImport.update({
  id: '/groups/nodes/',
  path: '/groups/nodes/',
  getParentRoute: () => rootRoute,
} as any)

const GroupsNodesGroupRoute = GroupsNodesGroupImport.update({
  id: '/groups/nodes/$group',
  path: '/groups/nodes/$group',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/floorplan': {
      id: '/floorplan'
      path: '/floorplan'
      fullPath: '/floorplan'
      preLoaderRoute: typeof FloorplanImport
      parentRoute: typeof rootRoute
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkImport
      parentRoute: typeof rootRoute
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/account/create': {
      id: '/account/create'
      path: '/account/create'
      fullPath: '/account/create'
      preLoaderRoute: typeof AccountCreateImport
      parentRoute: typeof rootRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginImport
      parentRoute: typeof rootRoute
    }
    '/add/image': {
      id: '/add/image'
      path: '/add/image'
      fullPath: '/add/image'
      preLoaderRoute: typeof AddImageImport
      parentRoute: typeof rootRoute
    }
    '/add/node': {
      id: '/add/node'
      path: '/add/node'
      fullPath: '/add/node'
      preLoaderRoute: typeof AddNodeImport
      parentRoute: typeof rootRoute
    }
    '/add/template': {
      id: '/add/template'
      path: '/add/template'
      fullPath: '/add/template'
      preLoaderRoute: typeof AddTemplateImport
      parentRoute: typeof rootRoute
    }
    '/images/$image': {
      id: '/images/$image'
      path: '/images/$image'
      fullPath: '/images/$image'
      preLoaderRoute: typeof ImagesImageImport
      parentRoute: typeof rootRoute
    }
    '/nodes/$node': {
      id: '/nodes/$node'
      path: '/nodes/$node'
      fullPath: '/nodes/$node'
      preLoaderRoute: typeof NodesNodeImport
      parentRoute: typeof rootRoute
    }
    '/rack/$rack': {
      id: '/rack/$rack'
      path: '/rack/$rack'
      fullPath: '/rack/$rack'
      preLoaderRoute: typeof RackRackImport
      parentRoute: typeof rootRoute
    }
    '/templates/$template': {
      id: '/templates/$template'
      path: '/templates/$template'
      fullPath: '/templates/$template'
      preLoaderRoute: typeof TemplatesTemplateImport
      parentRoute: typeof rootRoute
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesIndexImport
      parentRoute: typeof rootRoute
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesIndexImport
      parentRoute: typeof rootRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/groups/nodes/$group': {
      id: '/groups/nodes/$group'
      path: '/groups/nodes/$group'
      fullPath: '/groups/nodes/$group'
      preLoaderRoute: typeof GroupsNodesGroupImport
      parentRoute: typeof rootRoute
    }
    '/groups/nodes/': {
      id: '/groups/nodes/'
      path: '/groups/nodes'
      fullPath: '/groups/nodes'
      preLoaderRoute: typeof GroupsNodesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/floorplan': typeof FloorplanRoute
  '/network': typeof NetworkRoute
  '/power': typeof PowerRoute
  '/search': typeof SearchRoute
  '/account/create': typeof AccountCreateRoute
  '/account/login': typeof AccountLoginRoute
  '/add/image': typeof AddImageRoute
  '/add/node': typeof AddNodeRoute
  '/add/template': typeof AddTemplateRoute
  '/images/$image': typeof ImagesImageRoute
  '/nodes/$node': typeof NodesNodeRoute
  '/rack/$rack': typeof RackRackRoute
  '/templates/$template': typeof TemplatesTemplateRoute
  '/images': typeof ImagesIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/groups/nodes/$group': typeof GroupsNodesGroupRoute
  '/groups/nodes': typeof GroupsNodesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/floorplan': typeof FloorplanRoute
  '/network': typeof NetworkRoute
  '/power': typeof PowerRoute
  '/search': typeof SearchRoute
  '/account/create': typeof AccountCreateRoute
  '/account/login': typeof AccountLoginRoute
  '/add/image': typeof AddImageRoute
  '/add/node': typeof AddNodeRoute
  '/add/template': typeof AddTemplateRoute
  '/images/$image': typeof ImagesImageRoute
  '/nodes/$node': typeof NodesNodeRoute
  '/rack/$rack': typeof RackRackRoute
  '/templates/$template': typeof TemplatesTemplateRoute
  '/images': typeof ImagesIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/groups/nodes/$group': typeof GroupsNodesGroupRoute
  '/groups/nodes': typeof GroupsNodesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/floorplan': typeof FloorplanRoute
  '/network': typeof NetworkRoute
  '/power': typeof PowerRoute
  '/search': typeof SearchRoute
  '/account/create': typeof AccountCreateRoute
  '/account/login': typeof AccountLoginRoute
  '/add/image': typeof AddImageRoute
  '/add/node': typeof AddNodeRoute
  '/add/template': typeof AddTemplateRoute
  '/images/$image': typeof ImagesImageRoute
  '/nodes/$node': typeof NodesNodeRoute
  '/rack/$rack': typeof RackRackRoute
  '/templates/$template': typeof TemplatesTemplateRoute
  '/images/': typeof ImagesIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/groups/nodes/$group': typeof GroupsNodesGroupRoute
  '/groups/nodes/': typeof GroupsNodesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/floorplan'
    | '/network'
    | '/power'
    | '/search'
    | '/account/create'
    | '/account/login'
    | '/add/image'
    | '/add/node'
    | '/add/template'
    | '/images/$image'
    | '/nodes/$node'
    | '/rack/$rack'
    | '/templates/$template'
    | '/images'
    | '/nodes'
    | '/templates'
    | '/groups/nodes/$group'
    | '/groups/nodes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/floorplan'
    | '/network'
    | '/power'
    | '/search'
    | '/account/create'
    | '/account/login'
    | '/add/image'
    | '/add/node'
    | '/add/template'
    | '/images/$image'
    | '/nodes/$node'
    | '/rack/$rack'
    | '/templates/$template'
    | '/images'
    | '/nodes'
    | '/templates'
    | '/groups/nodes/$group'
    | '/groups/nodes'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/floorplan'
    | '/network'
    | '/power'
    | '/search'
    | '/account/create'
    | '/account/login'
    | '/add/image'
    | '/add/node'
    | '/add/template'
    | '/images/$image'
    | '/nodes/$node'
    | '/rack/$rack'
    | '/templates/$template'
    | '/images/'
    | '/nodes/'
    | '/templates/'
    | '/groups/nodes/$group'
    | '/groups/nodes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  FloorplanRoute: typeof FloorplanRoute
  NetworkRoute: typeof NetworkRoute
  PowerRoute: typeof PowerRoute
  SearchRoute: typeof SearchRoute
  AccountCreateRoute: typeof AccountCreateRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AddImageRoute: typeof AddImageRoute
  AddNodeRoute: typeof AddNodeRoute
  AddTemplateRoute: typeof AddTemplateRoute
  ImagesImageRoute: typeof ImagesImageRoute
  NodesNodeRoute: typeof NodesNodeRoute
  RackRackRoute: typeof RackRackRoute
  TemplatesTemplateRoute: typeof TemplatesTemplateRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  GroupsNodesGroupRoute: typeof GroupsNodesGroupRoute
  GroupsNodesIndexRoute: typeof GroupsNodesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  FloorplanRoute: FloorplanRoute,
  NetworkRoute: NetworkRoute,
  PowerRoute: PowerRoute,
  SearchRoute: SearchRoute,
  AccountCreateRoute: AccountCreateRoute,
  AccountLoginRoute: AccountLoginRoute,
  AddImageRoute: AddImageRoute,
  AddNodeRoute: AddNodeRoute,
  AddTemplateRoute: AddTemplateRoute,
  ImagesImageRoute: ImagesImageRoute,
  NodesNodeRoute: NodesNodeRoute,
  RackRackRoute: RackRackRoute,
  TemplatesTemplateRoute: TemplatesTemplateRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  GroupsNodesGroupRoute: GroupsNodesGroupRoute,
  GroupsNodesIndexRoute: GroupsNodesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/floorplan",
        "/network",
        "/power",
        "/search",
        "/account/create",
        "/account/login",
        "/add/image",
        "/add/node",
        "/add/template",
        "/images/$image",
        "/nodes/$node",
        "/rack/$rack",
        "/templates/$template",
        "/images/",
        "/nodes/",
        "/templates/",
        "/groups/nodes/$group",
        "/groups/nodes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/floorplan": {
      "filePath": "floorplan.tsx"
    },
    "/network": {
      "filePath": "network.tsx"
    },
    "/power": {
      "filePath": "power.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/account/create": {
      "filePath": "account/create.tsx"
    },
    "/account/login": {
      "filePath": "account/login.tsx"
    },
    "/add/image": {
      "filePath": "add/image.tsx"
    },
    "/add/node": {
      "filePath": "add/node.tsx"
    },
    "/add/template": {
      "filePath": "add/template.tsx"
    },
    "/images/$image": {
      "filePath": "images/$image.tsx"
    },
    "/nodes/$node": {
      "filePath": "nodes/$node.tsx"
    },
    "/rack/$rack": {
      "filePath": "rack/$rack.tsx"
    },
    "/templates/$template": {
      "filePath": "templates/$template.tsx"
    },
    "/images/": {
      "filePath": "images/index.tsx"
    },
    "/nodes/": {
      "filePath": "nodes/index.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    },
    "/groups/nodes/$group": {
      "filePath": "groups/nodes/$group.tsx"
    },
    "/groups/nodes/": {
      "filePath": "groups/nodes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
