// This file is auto-generated by @hey-api/openapi-ts

export const HostSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        provision: {
            type: 'boolean'
        },
        firmware: {
            type: 'string'
        },
        boot_image: {
            type: 'string'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        interfaces: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/NetInterface'
            }
        }
    }
} as const;

export const NetInterfaceSchema = {
    type: 'object',
    properties: {
        mac: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        ip: {
            type: 'string'
        },
        fqdn: {
            type: 'string'
        },
        bmc: {
            type: 'boolean'
        }
    }
} as const;

export const BootImageSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        kernel: {
            type: 'string'
        },
        initrd: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        liveimg: {
            type: 'string'
        },
        cmdline: {
            type: 'string'
        },
        verify: {
            type: 'boolean'
        }
    }
} as const;

export const UserSchema = {
    required: ['username'],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        password_hash: {
            type: 'string'
        },
        role: {
            type: 'string'
        }
    }
} as const;

export const DataDumpSchema = {
    required: ['hosts'],
    type: 'object',
    properties: {
        users: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/User'
            }
        },
        images: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BootImage'
            }
        },
        hosts: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Host'
            }
        }
    }
} as const;

export const ErrorResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;