// This file is auto-generated by @hey-api/openapi-ts

export type Host = {
    id?: string;
    name: string;
    provision?: boolean;
    firmware?: string;
    boot_image?: string;
    tags?: Array<(string)>;
    interfaces?: Array<NetInterface>;
};

export type NetInterface = {
    mac?: string;
    name?: string;
    ip?: string;
    fqdn?: string;
    bmc?: boolean;
};

export type BootImage = {
    id?: string;
    name: string;
    kernel?: string;
    initrd?: Array<(string)>;
    liveimg?: string;
    cmdline?: string;
    verify?: boolean;
};

export type User = {
    id?: string;
    username: string;
    password_hash?: string;
    role?: string;
};

export type DataDump = {
    users?: Array<User>;
    images?: Array<BootImage>;
    hosts: Array<Host>;
};

export type ErrorResponse = {
    message?: string;
};

export type HostListResponse = (Array<Host>);

export type HostListError = (ErrorResponse);

export type HostFindData = {
    path: {
        /**
         * nodeset syntax. Example: cpn-d13-[01-100]
         */
        nodeSet: string;
    };
};

export type HostFindResponse = (Array<Host>);

export type HostFindError = (ErrorResponse);

export type HostDeleteData = {
    path: {
        /**
         * nodeset syntax. Example: cpn-d13-[01-100]
         */
        nodeSet: string;
    };
};

export type HostDeleteResponse = (unknown);

export type HostDeleteError = (ErrorResponse);

export type HostTagsData = {
    path: {
        /**
         * comman separated list of tags. Example: ib,noib,k16
         */
        tags: string;
    };
};

export type HostTagsResponse = (Array<Host>);

export type HostTagsError = (ErrorResponse);

export type HostProvisionData = {
    path: {
        /**
         * nodeset syntax. Example: cpn-d13-[01-100]
         */
        nodeSet: string;
    };
};

export type HostProvisionResponse = (unknown);

export type HostProvisionError = (ErrorResponse);

export type HostUnprovisionData = {
    path: {
        /**
         * nodeset syntax. Example: cpn-d13-[01-100]
         */
        nodeSet: string;
    };
};

export type HostUnprovisionResponse = (unknown);

export type HostUnprovisionError = (ErrorResponse);

export type HostTagData = {
    path: {
        /**
         * nodeset syntax. Example: cpn-d13-[01-100]
         */
        nodeSet: string;
    };
    query: {
        /**
         * list of tags. Example: ib,noib,k16
         */
        tags: string;
    };
};

export type HostTagResponse = (unknown);

export type HostTagError = (ErrorResponse);

export type HostUntagData = {
    path: {
        /**
         * nodeset syntax. Example: cpn-d13-[01-100]
         */
        nodeSet: string;
    };
    query: {
        /**
         * list of tags. Example: ib,noib,k16
         */
        tags: string;
    };
};

export type HostUntagResponse = (unknown);

export type HostUntagError = (ErrorResponse);

export type StoreHostsData = {
    /**
     * Add/Update one or more hosts to Grendel
     */
    body: Array<Host>;
};

export type StoreHostsResponse = (unknown);

export type StoreHostsError = (ErrorResponse);

export type UserListResponse = (Array<User>);

export type UserListError = (ErrorResponse);

export type ImageListResponse = (Array<BootImage>);

export type ImageListError = (ErrorResponse);

export type ImageFindData = {
    path: {
        /**
         * Name of image
         */
        name: string;
    };
};

export type ImageFindResponse = (Array<BootImage>);

export type ImageFindError = (ErrorResponse);

export type ImageDeleteData = {
    path: {
        /**
         * Name of boot image to delete
         */
        name: string;
    };
};

export type ImageDeleteResponse = (unknown);

export type ImageDeleteError = (ErrorResponse);

export type StoreImagesData = {
    /**
     * Add/Update one or more images to Grendel
     */
    body: Array<BootImage>;
};

export type StoreImagesResponse = (unknown);

export type StoreImagesError = (ErrorResponse);

export type RestoreData = {
    /**
     * Restore grendel database from dump
     */
    body: DataDump;
};

export type RestoreResponse = (unknown);

export type RestoreError = (ErrorResponse);