// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://0.0.0.0:8080' | (string & {});
};

/**
 * AuthRequest schema
 */
export type AuthRequest = {
    password?: string;
    username?: string;
};

/**
 * AuthResetRequest schema
 */
export type AuthResetRequest = {
    current_password?: string;
    new_password: string;
};

/**
 * AuthResponse schema
 */
export type AuthResponse = {
    expire?: number;
    role?: string;
    token?: string;
    username?: string;
};

/**
 * AuthSignupRequest schema
 */
export type AuthSignupRequest = {
    password: string;
    username: string;
};

/**
 * AuthTokenReponse schema
 */
export type AuthTokenReponse = {
    token?: string;
};

/**
 * AuthTokenRequest schema
 */
export type AuthTokenRequest = {
    /**
     * string parsed by time.ParseDuration, examples include: infinite, 8h, 30m, 20s
     */
    expire?: string;
    /**
     * type of model.Role, valid options: disabled, user, admin
     */
    role?: string;
    /**
     * username shown in logs, does not need to be a valid user in the DB
     */
    username?: string;
};

/**
 * BmcDellInstallFromRepoRequest schema
 */
export type BmcDellInstallFromRepoRequest = {
    /**
     * ApplyUpdate false will only check for firmware upgrades. true will queue the update installs as a job.
     */
    ApplyUpdate?: boolean;
    CatalogFile?: string;
    /**
     * clear job queue before submitting request. ApplyUpdate must be true
     */
    ClearJobQueue?: boolean;
    /**
     * domain name or IP address of share
     */
    IPAddress?: string;
    /**
     * false = share needs valid HTTPS cert, true = allow invalid certs
     */
    IgnoreCertWarning?: boolean;
    /**
     * false = do not reboot node automatically, jobs will queue as scheduled and wait until next boot. true = reboot when needed
     */
    RebootNeeded?: boolean;
    ShareName?: string;
    /**
     * type of share
     */
    ShareType?: string;
};

/**
 * BmcImportConfigurationRequest schema
 */
export type BmcImportConfigurationRequest = {
    /**
     * template file relative to templates directory
     */
    file?: string;
    /**
     * options include: NoReboot, Graceful, Forced
     */
    shutdown_type?: string;
};

/**
 * BmcJobDeleteRequest schema
 */
export type BmcJobDeleteRequest = {
    /**
     * Map with Node and Redfish Job IDs. Use 'JID_CLEARALL' to clear all jobs
     */
    node_job_list?: {
        [key: string]: Array<string>;
    };
};

/**
 * BmcOsPowerBody schema
 */
export type BmcOsPowerBody = {
    /**
     * string of type schemas.BootSourceOverrideTarget. Common options include: None, Pxe, BiosSetup, Utilities, Diags
     */
    boot_option?: string;
    /**
     * string of type schemas.ResetType. Common options include: On, ForceOn, ForceOff, ForceRestart, GracefulRestart, GracefulShutdown, PowerCycle
     */
    power_option?: string;
};

/**
 * BootImage schema
 */
export type BootImage = {
    cmdline?: string;
    id?: number;
    initrd?: Array<string>;
    kernel: string;
    liveimg?: string;
    name: string;
    provision_templates?: {
        [key: string]: string;
    };
    uid?: string;
    verify?: boolean;
};

/**
 * BootImageAddRequest schema
 */
export type BootImageAddRequest = {
    boot_images?: Array<{
        cmdline?: string;
        id?: number;
        initrd?: Array<string>;
        kernel?: string;
        liveimg?: string;
        name?: string;
        provision_templates?: {
            [key: string]: string;
        };
        uid?: string;
        verify?: boolean;
    }>;
};

/**
 * DataDump schema
 */
export type DataDump = {
    Hosts?: Array<{
        bonds?: Array<{
            bmc?: boolean;
            fqdn?: string;
            id?: number;
            ifname?: string;
            ip?: string;
            mac?: string;
            mtu?: number;
            peers?: Array<string>;
            vlan?: string;
        }>;
        boot_image?: string;
        firmware?: string;
        id?: number;
        interfaces?: Array<{
            bmc?: boolean;
            fqdn?: string;
            id?: number;
            ifname?: string;
            ip?: string;
            mac?: string;
            mtu?: number;
            vlan?: string;
        }>;
        name?: string;
        provision?: boolean;
        tags?: Array<string>;
        uid?: string;
    }>;
    Images?: Array<{
        cmdline?: string;
        id?: number;
        initrd?: Array<string>;
        kernel?: string;
        liveimg?: string;
        name?: string;
        provision_templates?: {
            [key: string]: string;
        };
        uid?: string;
        verify?: boolean;
    }>;
    Users?: Array<{
        created_at?: string;
        enabled?: boolean;
        hash?: string;
        id?: number;
        modified_at?: string;
        role?: string;
        username?: string;
    }>;
};

/**
 * Event schema
 */
export type Event = {
    JobMessages?: Array<{
        data?: string;
        host?: string;
        msg?: string;
        redfish_error?: {
            code?: string;
            error?: {
                '@Message.ExtendedInfo'?: Array<{
                    Message?: string;
                    'MessageArgs.@odata.count'?: number;
                    MessageId?: string;
                    'RelatedProperties.@odata.count'?: number;
                    Resolution?: string;
                    Severity?: string;
                }>;
                code?: string;
                message?: string;
            };
        };
        status?: string;
    }>;
    Message?: string;
    Severity?: string;
    Time?: string;
    User?: string;
};

/**
 * GenericResponse schema
 */
export type GenericResponse = {
    changed?: number;
    detail?: string;
    title?: string;
};

/**
 * GetRolesResponse schema
 */
export type GetRolesResponse = {
    roles?: Array<{
        name?: string;
        permission_list?: Array<{
            method?: string;
            path?: string;
        }>;
        unassigned_permission_list?: Array<{
            method?: string;
            path?: string;
        }>;
    }>;
};

/**
 * HTTPError schema
 */
export type HttpError = {
    /**
     * Human readable error message
     */
    detail?: string;
    errors?: Array<{
        more?: {
            [key: string]: unknown;
        };
        name?: string;
        reason?: string;
    }>;
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * Short title of the error
     */
    title?: string;
    /**
     * URL of the error type. Can be used to lookup the error in a documentation
     */
    type?: string;
};

/**
 * Host schema
 */
export type Host = {
    bonds?: Array<{
        bmc?: boolean;
        fqdn?: string;
        id?: number;
        ifname?: string;
        ip?: string;
        mac?: string;
        mtu?: number;
        peers?: Array<string>;
        vlan?: string;
    }>;
    boot_image?: string;
    firmware?: string;
    id?: number;
    interfaces?: Array<{
        bmc?: boolean;
        fqdn?: string;
        id?: number;
        ifname?: string;
        ip?: string;
        mac?: string;
        mtu?: number;
        vlan?: string;
    }>;
    name?: string;
    provision?: boolean;
    tags?: Array<string>;
    uid?: string;
};

/**
 * JobMessage schema
 */
export type JobMessage = {
    data?: string;
    host?: string;
    msg?: string;
    redfish_error?: {
        code?: string;
        error?: {
            '@Message.ExtendedInfo'?: Array<{
                Message?: string;
                'MessageArgs.@odata.count'?: number;
                MessageId?: string;
                'RelatedProperties.@odata.count'?: number;
                Resolution?: string;
                Severity?: string;
            }>;
            code?: string;
            message?: string;
        };
    };
    status?: string;
};

/**
 * LLDP schema
 */
export type Lldp = {
    chassis_id?: string;
    chassis_id_type?: string;
    management_address?: string;
    port_description?: string;
    port_id?: string;
    port_id_type?: string;
    port_name?: string;
    system_description?: string;
    system_name?: string;
};

/**
 * NodeAddRequest schema
 */
export type NodeAddRequest = {
    node_list?: Array<{
        bonds?: Array<{
            bmc?: boolean;
            fqdn?: string;
            id?: number;
            ifname?: string;
            ip?: string;
            mac?: string;
            mtu?: number;
            peers?: Array<string>;
            vlan?: string;
        }>;
        boot_image?: string;
        firmware?: string;
        id?: number;
        interfaces?: Array<{
            bmc?: boolean;
            fqdn?: string;
            id?: number;
            ifname?: string;
            ip?: string;
            mac?: string;
            mtu?: number;
            vlan?: string;
        }>;
        name?: string;
        provision?: boolean;
        tags?: Array<string>;
        uid?: string;
    }>;
};

/**
 * NodeBootImageRequest schema
 */
export type NodeBootImageRequest = {
    image?: string;
};

/**
 * NodeBootTokenResponse schema
 */
export type NodeBootTokenResponse = {
    nodes?: Array<{
        name?: string;
        token?: string;
    }>;
};

/**
 * NodeProvisionRequest schema
 */
export type NodeProvisionRequest = {
    provision?: boolean;
};

/**
 * NodeTagsRequest schema
 */
export type NodeTagsRequest = {
    /**
     * comma separated list of tags
     */
    tags?: string;
};

/**
 * PatchRolesRequest schema
 */
export type PatchRolesRequest = {
    permission_list?: Array<{
        method?: string;
        path?: string;
    }>;
    role?: string;
};

/**
 * PostRolesRequest schema
 */
export type PostRolesRequest = {
    inherited_role?: string;
    role?: string;
};

/**
 * RedfishDellUpgradeFirmware schema
 */
export type RedfishDellUpgradeFirmware = {
    Message?: string;
    Name?: string;
    Status?: string;
    UpdateCount?: number;
    UpdateList?: Array<{
        BaseLocation?: string;
        ComponentID?: string;
        ComponentInfoName?: string;
        ComponentInfoValue?: string;
        ComponentType?: string;
        Criticality?: string;
        DisplayName?: string;
        InstalledVersion?: string;
        JobID?: string;
        Name?: string;
        PackageName?: string;
        PackagePath?: string;
        PackageVersion?: string;
        RebootType?: string;
        Target?: string;
    }>;
    UpdateRebootType?: string;
};

/**
 * RedfishJob schema
 */
export type RedfishJob = {
    jobs?: Array<{
        '@Message.ExtendedInfo'?: Array<{
            Message?: string;
            MessageArgs?: Array<string>;
            MessageId?: string;
            MessageSeverity?: string;
            Oem?: unknown;
            RelatedProperties?: Array<string>;
            Resolution?: string;
            ResolutionSteps?: Array<{
                ActionParameters?: Array<{
                    AllowableNumbers?: Array<string>;
                    AllowablePattern?: string;
                    AllowableValueDescriptions?: Array<string>;
                    AllowableValues?: Array<string>;
                    ArraySizeMaximum?: number;
                    ArraySizeMinimum?: number;
                    DataType?: string;
                    DefaultValue?: string;
                    MaximumValue?: number;
                    MinimumValue?: number;
                    Name?: string;
                    NoDefaultValue?: boolean;
                    ObjectDataType?: string;
                    Required?: boolean;
                }>;
                ActionURI?: string;
                Oem?: unknown;
                Priority?: number;
                ResolutionType?: string;
                RetryCount?: number;
                RetryIntervalSeconds?: number;
                TargetComponentURI?: string;
            }>;
            Severity?: string;
            UserAuthenticationSource?: string;
            Username?: string;
        }>;
        '@odata.context'?: string;
        '@odata.etag'?: string;
        '@odata.id'?: string;
        '@odata.type'?: string;
        CreatedBy?: string;
        CreationTime?: string;
        Description?: string;
        EndTime?: string;
        EstimatedCompletionTime?: string;
        EstimatedDuration?: string;
        HidePayload?: boolean;
        Id?: string;
        JobPriority?: number;
        JobState?: string;
        JobStatus?: string;
        JobType?: string;
        MaxExecutionTime?: string;
        Messages?: Array<{
            Message?: string;
            MessageArgs?: Array<string>;
            MessageId?: string;
            MessageSeverity?: string;
            Oem?: unknown;
            RelatedProperties?: Array<string>;
            Resolution?: string;
            ResolutionSteps?: Array<{
                ActionParameters?: Array<{
                    AllowableNumbers?: Array<string>;
                    AllowablePattern?: string;
                    AllowableValueDescriptions?: Array<string>;
                    AllowableValues?: Array<string>;
                    ArraySizeMaximum?: number;
                    ArraySizeMinimum?: number;
                    DataType?: string;
                    DefaultValue?: string;
                    MaximumValue?: number;
                    MinimumValue?: number;
                    Name?: string;
                    NoDefaultValue?: boolean;
                    ObjectDataType?: string;
                    Required?: boolean;
                }>;
                ActionURI?: string;
                Oem?: unknown;
                Priority?: number;
                ResolutionType?: string;
                RetryCount?: number;
                RetryIntervalSeconds?: number;
                TargetComponentURI?: string;
            }>;
            Severity?: string;
            UserAuthenticationSource?: string;
            Username?: string;
        }>;
        Name?: string;
        Oem?: unknown;
        Parameters?: {
            [key: string]: unknown;
        };
        Payload?: {
            HttpHeaders?: Array<string>;
            HttpOperation?: string;
            JsonBody?: string;
            TargetUri?: string;
        };
        PercentComplete?: number;
        RawData?: string;
        Schedule?: {
            EnabledDaysOfMonth?: Array<number>;
            EnabledDaysOfWeek?: Array<string>;
            EnabledIntervals?: Array<string>;
            EnabledMonthsOfYear?: Array<string>;
            InitialStartTime?: string;
            Lifetime?: string;
            MaxOccurrences?: number;
            Name?: string;
            RecurrenceInterval?: string;
        };
        StartTime?: string;
        StepOrder?: Array<string>;
    }>;
    name?: string;
};

/**
 * RedfishMetricReport schema
 */
export type RedfishMetricReport = {
    name?: string;
    reports?: Array<{
        '@Message.ExtendedInfo'?: Array<{
            Message?: string;
            MessageArgs?: Array<string>;
            MessageId?: string;
            MessageSeverity?: string;
            Oem?: unknown;
            RelatedProperties?: Array<string>;
            Resolution?: string;
            ResolutionSteps?: Array<{
                ActionParameters?: Array<{
                    AllowableNumbers?: Array<string>;
                    AllowablePattern?: string;
                    AllowableValueDescriptions?: Array<string>;
                    AllowableValues?: Array<string>;
                    ArraySizeMaximum?: number;
                    ArraySizeMinimum?: number;
                    DataType?: string;
                    DefaultValue?: string;
                    MaximumValue?: number;
                    MinimumValue?: number;
                    Name?: string;
                    NoDefaultValue?: boolean;
                    ObjectDataType?: string;
                    Required?: boolean;
                }>;
                ActionURI?: string;
                Oem?: unknown;
                Priority?: number;
                ResolutionType?: string;
                RetryCount?: number;
                RetryIntervalSeconds?: number;
                TargetComponentURI?: string;
            }>;
            Severity?: string;
            UserAuthenticationSource?: string;
            Username?: string;
        }>;
        '@odata.context'?: string;
        '@odata.etag'?: string;
        '@odata.id'?: string;
        '@odata.type'?: string;
        Context?: string;
        Description?: string;
        Id?: string;
        MetricValues?: Array<{
            MetricId?: string;
            MetricProperty?: string;
            MetricValue?: string;
            Oem?: unknown;
            Timestamp?: string;
        }>;
        Name?: string;
        Oem?: unknown;
        ReportSequence?: string;
        Timestamp?: string;
    }>;
};

/**
 * RedfishSystem schema
 */
export type RedfishSystem = {
    bios_version?: string;
    boot_next?: string;
    boot_order?: Array<string>;
    health?: string;
    host_name?: string;
    manufacturer?: string;
    model?: string;
    name?: string;
    oem_dell?: {
        '@Message.ExtendedInfo'?: Array<{
            Message?: string;
            MessageArgs?: Array<string>;
            MessageId?: string;
            MessageSeverity?: string;
            Oem?: unknown;
            RelatedProperties?: Array<string>;
            Resolution?: string;
            ResolutionSteps?: Array<{
                ActionParameters?: Array<{
                    AllowableNumbers?: Array<string>;
                    AllowablePattern?: string;
                    AllowableValueDescriptions?: Array<string>;
                    AllowableValues?: Array<string>;
                    ArraySizeMaximum?: number;
                    ArraySizeMinimum?: number;
                    DataType?: string;
                    DefaultValue?: string;
                    MaximumValue?: number;
                    MinimumValue?: number;
                    Name?: string;
                    NoDefaultValue?: boolean;
                    ObjectDataType?: string;
                    Required?: boolean;
                }>;
                ActionURI?: string;
                Oem?: unknown;
                Priority?: number;
                ResolutionType?: string;
                RetryCount?: number;
                RetryIntervalSeconds?: number;
                TargetComponentURI?: string;
            }>;
            Severity?: string;
            UserAuthenticationSource?: string;
            Username?: string;
        }>;
        '@odata.context'?: string;
        '@odata.etag'?: string;
        '@odata.id'?: string;
        '@odata.type'?: string;
        BIOSReleaseDate?: string;
        BaseBoardChassisSlot?: string;
        BatteryRollupStatus?: string;
        BladeGeometry?: string;
        CMCIP?: string;
        CPURollupStatus?: string;
        ChassisModel?: string;
        ChassisName?: string;
        ChassisServiceTag?: string;
        ChassisSystemHeightUnit?: number;
        CurrentRollupStatus?: string;
        Description?: string;
        EstimatedExhaustTemperatureCelsius?: number;
        EstimatedSystemAirflowCFM?: number;
        ExpressServiceCode?: string;
        FanRollupStatus?: string;
        IDSDMRollupStatus?: string;
        Id?: string;
        IntrusionRollupStatus?: string;
        IsOEMBranded?: string;
        LastSystemInventoryTime?: string;
        LastUpdateTime?: string;
        LicensingRollupStatus?: string;
        ManagedSystemSize?: string;
        MaxCPUSockets?: number;
        MaxDIMMSlots?: number;
        MaxPCIeSlots?: number;
        MemoryOperationMode?: string;
        Name?: string;
        NodeID?: string;
        Oem?: unknown;
        PSRollupStatus?: string;
        PlatformGUID?: string;
        PopulatedDIMMSlots?: number;
        PopulatedPCIeSlots?: number;
        PowerCapEnabledState?: string;
        SDCardRollupStatus?: string;
        SELRollupStatus?: string;
        ServerAllocationWatts?: number;
        StorageRollupStatus?: string;
        SysMemErrorMethodology?: string;
        SysMemFailOverState?: string;
        SysMemLocation?: string;
        SysMemPrimaryStatus?: string;
        SystemGeneration?: string;
        SystemID?: number;
        SystemRevision?: string;
        TempRollupStatus?: string;
        TempStatisticsRollupStatus?: string;
        UUID?: string;
        VoltRollupStatus?: string;
        smbiosGUID?: string;
    };
    power_status?: string;
    processor_count?: number;
    serial_number?: string;
    total_memory?: number;
};

/**
 * User schema
 */
export type User = {
    created_at?: string;
    enabled?: boolean;
    hash?: string;
    id?: number;
    modified_at?: string;
    role?: string;
    username?: string;
};

/**
 * UserEnableRequest schema
 */
export type UserEnableRequest = {
    enabled?: boolean;
};

/**
 * UserRoleRequest schema
 */
export type UserRoleRequest = {
    /**
     * type of model.Role, valid options: disabled, user, admin
     */
    role?: string;
};

/**
 * UserStoreRequest schema
 */
export type UserStoreRequest = {
    password?: string;
    username?: string;
};

/**
 * UserStoreResponse schema
 */
export type UserStoreResponse = {
    role?: string;
    username?: string;
};

/**
 * unknown-interface schema
 */
export type UnknownInterface = unknown;

export type PatchV1AuthResetData = {
    /**
     * Request body for api.AuthResetRequest
     */
    body: AuthResetRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/reset';
};

export type PatchV1AuthResetErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PatchV1AuthResetError = PatchV1AuthResetErrors[keyof PatchV1AuthResetErrors];

export type PatchV1AuthResetResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PatchV1AuthResetResponse = PatchV1AuthResetResponses[keyof PatchV1AuthResetResponses];

export type PostV1AuthSigninData = {
    /**
     * Request body for api.AuthRequest
     */
    body: AuthRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/signin';
};

export type PostV1AuthSigninErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1AuthSigninError = PostV1AuthSigninErrors[keyof PostV1AuthSigninErrors];

export type PostV1AuthSigninResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostV1AuthSigninResponse = PostV1AuthSigninResponses[keyof PostV1AuthSigninResponses];

export type DeleteV1AuthSignoutData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/signout';
};

export type DeleteV1AuthSignoutErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1AuthSignoutError = DeleteV1AuthSignoutErrors[keyof DeleteV1AuthSignoutErrors];

export type DeleteV1AuthSignoutResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type DeleteV1AuthSignoutResponse = DeleteV1AuthSignoutResponses[keyof DeleteV1AuthSignoutResponses];

export type PostV1AuthSignupData = {
    /**
     * Request body for api.AuthSignupRequest
     */
    body: AuthSignupRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type PostV1AuthSignupErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1AuthSignupError = PostV1AuthSignupErrors[keyof PostV1AuthSignupErrors];

export type PostV1AuthSignupResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostV1AuthSignupResponse = PostV1AuthSignupResponses[keyof PostV1AuthSignupResponses];

export type PostV1AuthTokenData = {
    /**
     * Request body for api.AuthTokenRequest
     */
    body: AuthTokenRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/token';
};

export type PostV1AuthTokenErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1AuthTokenError = PostV1AuthTokenErrors[keyof PostV1AuthTokenErrors];

export type PostV1AuthTokenResponses = {
    /**
     * OK
     */
    200: AuthTokenReponse;
};

export type PostV1AuthTokenResponse = PostV1AuthTokenResponses[keyof PostV1AuthTokenResponses];

export type GetV1BmcData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc';
};

export type GetV1BmcErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1BmcError = GetV1BmcErrors[keyof GetV1BmcErrors];

export type GetV1BmcResponses = {
    /**
     * OK
     */
    200: Array<RedfishSystem>;
};

export type GetV1BmcResponse = GetV1BmcResponses[keyof GetV1BmcResponses];

export type PostV1BmcConfigureAutoData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/configure/auto';
};

export type PostV1BmcConfigureAutoErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1BmcConfigureAutoError = PostV1BmcConfigureAutoErrors[keyof PostV1BmcConfigureAutoErrors];

export type PostV1BmcConfigureAutoResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type PostV1BmcConfigureAutoResponse = PostV1BmcConfigureAutoResponses[keyof PostV1BmcConfigureAutoResponses];

export type PostV1BmcConfigureImportData = {
    /**
     * Request body for api.BmcImportConfigurationRequest
     */
    body: BmcImportConfigurationRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/configure/import';
};

export type PostV1BmcConfigureImportErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1BmcConfigureImportError = PostV1BmcConfigureImportErrors[keyof PostV1BmcConfigureImportErrors];

export type PostV1BmcConfigureImportResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type PostV1BmcConfigureImportResponse = PostV1BmcConfigureImportResponses[keyof PostV1BmcConfigureImportResponses];

export type DeleteV1BmcJobsData = {
    /**
     * Request body for api.BmcJobDeleteRequest
     */
    body: BmcJobDeleteRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/jobs';
};

export type DeleteV1BmcJobsErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1BmcJobsError = DeleteV1BmcJobsErrors[keyof DeleteV1BmcJobsErrors];

export type DeleteV1BmcJobsResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type DeleteV1BmcJobsResponse = DeleteV1BmcJobsResponses[keyof DeleteV1BmcJobsResponses];

export type GetV1BmcJobsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/jobs';
};

export type GetV1BmcJobsErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1BmcJobsError = GetV1BmcJobsErrors[keyof GetV1BmcJobsErrors];

export type GetV1BmcJobsResponses = {
    /**
     * OK
     */
    200: Array<RedfishJob>;
};

export type GetV1BmcJobsResponse = GetV1BmcJobsResponses[keyof GetV1BmcJobsResponses];

export type DeleteV1BmcJobsJidsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        /**
         * Redfish Job IDs. Use 'JID_CLEARALL' to clear all jobs
         */
        jids: string;
    };
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/jobs/{jids}';
};

export type DeleteV1BmcJobsJidsErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1BmcJobsJidsError = DeleteV1BmcJobsJidsErrors[keyof DeleteV1BmcJobsJidsErrors];

export type DeleteV1BmcJobsJidsResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type DeleteV1BmcJobsJidsResponse = DeleteV1BmcJobsJidsResponses[keyof DeleteV1BmcJobsJidsResponses];

export type GetV1BmcMetricsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/metrics';
};

export type GetV1BmcMetricsErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1BmcMetricsError = GetV1BmcMetricsErrors[keyof GetV1BmcMetricsErrors];

export type GetV1BmcMetricsResponses = {
    /**
     * OK
     */
    200: Array<RedfishMetricReport>;
};

export type GetV1BmcMetricsResponse = GetV1BmcMetricsResponses[keyof GetV1BmcMetricsResponses];

export type PostV1BmcPowerBmcData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/power/bmc';
};

export type PostV1BmcPowerBmcErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1BmcPowerBmcError = PostV1BmcPowerBmcErrors[keyof PostV1BmcPowerBmcErrors];

export type PostV1BmcPowerBmcResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type PostV1BmcPowerBmcResponse = PostV1BmcPowerBmcResponses[keyof PostV1BmcPowerBmcResponses];

export type PostV1BmcPowerOsData = {
    /**
     * Request body for api.BmcOsPowerBody
     */
    body: BmcOsPowerBody;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/power/os';
};

export type PostV1BmcPowerOsErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1BmcPowerOsError = PostV1BmcPowerOsErrors[keyof PostV1BmcPowerOsErrors];

export type PostV1BmcPowerOsResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type PostV1BmcPowerOsResponse = PostV1BmcPowerOsResponses[keyof PostV1BmcPowerOsResponses];

export type DeleteV1BmcSelData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/sel';
};

export type DeleteV1BmcSelErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1BmcSelError = DeleteV1BmcSelErrors[keyof DeleteV1BmcSelErrors];

export type DeleteV1BmcSelResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type DeleteV1BmcSelResponse = DeleteV1BmcSelResponses[keyof DeleteV1BmcSelResponses];

export type PostV1BmcUpgradeDellInstallfromrepoData = {
    /**
     * Request body for api.BmcDellInstallFromRepoRequest
     */
    body: BmcDellInstallFromRepoRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/upgrade/dell/installfromrepo';
};

export type PostV1BmcUpgradeDellInstallfromrepoErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1BmcUpgradeDellInstallfromrepoError = PostV1BmcUpgradeDellInstallfromrepoErrors[keyof PostV1BmcUpgradeDellInstallfromrepoErrors];

export type PostV1BmcUpgradeDellInstallfromrepoResponses = {
    /**
     * OK
     */
    200: Array<JobMessage>;
};

export type PostV1BmcUpgradeDellInstallfromrepoResponse = PostV1BmcUpgradeDellInstallfromrepoResponses[keyof PostV1BmcUpgradeDellInstallfromrepoResponses];

export type GetV1BmcUpgradeDellRepoData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/bmc/upgrade/dell/repo';
};

export type GetV1BmcUpgradeDellRepoErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1BmcUpgradeDellRepoError = GetV1BmcUpgradeDellRepoErrors[keyof GetV1BmcUpgradeDellRepoErrors];

export type GetV1BmcUpgradeDellRepoResponses = {
    /**
     * OK
     */
    200: Array<RedfishDellUpgradeFirmware>;
};

export type GetV1BmcUpgradeDellRepoResponse = GetV1BmcUpgradeDellRepoResponses[keyof GetV1BmcUpgradeDellRepoResponses];

export type GetV1DbDumpData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/db/dump';
};

export type GetV1DbDumpErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1DbDumpError = GetV1DbDumpErrors[keyof GetV1DbDumpErrors];

export type GetV1DbDumpResponses = {
    /**
     * OK
     */
    200: DataDump;
};

export type GetV1DbDumpResponse = GetV1DbDumpResponses[keyof GetV1DbDumpResponses];

export type PostV1DbRestoreData = {
    /**
     * Request body for model.DataDump
     */
    body: DataDump;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/db/restore';
};

export type PostV1DbRestoreErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1DbRestoreError = PostV1DbRestoreErrors[keyof PostV1DbRestoreErrors];

export type PostV1DbRestoreResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PostV1DbRestoreResponse = PostV1DbRestoreResponses[keyof PostV1DbRestoreResponses];

export type GetV1GrendelEventsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/grendel/events';
};

export type GetV1GrendelEventsErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1GrendelEventsError = GetV1GrendelEventsErrors[keyof GetV1GrendelEventsErrors];

export type GetV1GrendelEventsResponses = {
    /**
     * OK
     */
    200: Array<Event>;
};

export type GetV1GrendelEventsResponse = GetV1GrendelEventsResponses[keyof GetV1GrendelEventsResponses];

export type DeleteV1ImagesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by name
         */
        names?: string;
    };
    url: '/v1/images';
};

export type DeleteV1ImagesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1ImagesError = DeleteV1ImagesErrors[keyof DeleteV1ImagesErrors];

export type DeleteV1ImagesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type DeleteV1ImagesResponse = DeleteV1ImagesResponses[keyof DeleteV1ImagesResponses];

export type GetV1ImagesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/images';
};

export type GetV1ImagesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1ImagesError = GetV1ImagesErrors[keyof GetV1ImagesErrors];

export type GetV1ImagesResponses = {
    /**
     * OK
     */
    200: Array<BootImage>;
};

export type GetV1ImagesResponse = GetV1ImagesResponses[keyof GetV1ImagesResponses];

export type PostV1ImagesData = {
    /**
     * Request body for api.BootImageAddRequest
     */
    body: BootImageAddRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/images';
};

export type PostV1ImagesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1ImagesError = PostV1ImagesErrors[keyof PostV1ImagesErrors];

export type PostV1ImagesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PostV1ImagesResponse = PostV1ImagesResponses[keyof PostV1ImagesResponses];

export type GetV1ImagesFindData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by name
         */
        names?: string;
    };
    url: '/v1/images/find';
};

export type GetV1ImagesFindErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1ImagesFindError = GetV1ImagesFindErrors[keyof GetV1ImagesFindErrors];

export type GetV1ImagesFindResponses = {
    /**
     * OK
     */
    200: Array<BootImage>;
};

export type GetV1ImagesFindResponse = GetV1ImagesFindResponses[keyof GetV1ImagesFindResponses];

export type DeleteV1NodesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/nodes';
};

export type DeleteV1NodesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1NodesError = DeleteV1NodesErrors[keyof DeleteV1NodesErrors];

export type DeleteV1NodesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type DeleteV1NodesResponse = DeleteV1NodesResponses[keyof DeleteV1NodesResponses];

export type GetV1NodesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/nodes';
};

export type GetV1NodesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1NodesError = GetV1NodesErrors[keyof GetV1NodesErrors];

export type GetV1NodesResponses = {
    /**
     * OK
     */
    200: Array<Host>;
};

export type GetV1NodesResponse = GetV1NodesResponses[keyof GetV1NodesResponses];

export type PostV1NodesData = {
    /**
     * Request body for api.NodeAddRequest
     */
    body: NodeAddRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/nodes';
};

export type PostV1NodesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1NodesError = PostV1NodesErrors[keyof PostV1NodesErrors];

export type PostV1NodesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PostV1NodesResponse = PostV1NodesResponses[keyof PostV1NodesResponses];

export type GetV1NodesFindData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/nodes/find';
};

export type GetV1NodesFindErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1NodesFindError = GetV1NodesFindErrors[keyof GetV1NodesFindErrors];

export type GetV1NodesFindResponses = {
    /**
     * OK
     */
    200: Array<Host>;
};

export type GetV1NodesFindResponse = GetV1NodesFindResponses[keyof GetV1NodesFindResponses];

export type PatchV1NodesImageData = {
    /**
     * Request body for api.NodeBootImageRequest
     */
    body: NodeBootImageRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/nodes/image';
};

export type PatchV1NodesImageErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PatchV1NodesImageError = PatchV1NodesImageErrors[keyof PatchV1NodesImageErrors];

export type PatchV1NodesImageResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PatchV1NodesImageResponse = PatchV1NodesImageResponses[keyof PatchV1NodesImageResponses];

export type PatchV1NodesProvisionData = {
    /**
     * Request body for api.NodeProvisionRequest
     */
    body: NodeProvisionRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/nodes/provision';
};

export type PatchV1NodesProvisionErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PatchV1NodesProvisionError = PatchV1NodesProvisionErrors[keyof PatchV1NodesProvisionErrors];

export type PatchV1NodesProvisionResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PatchV1NodesProvisionResponse = PatchV1NodesProvisionResponses[keyof PatchV1NodesProvisionResponses];

export type PatchV1NodesTagsActionData = {
    /**
     * Request body for api.NodeTagsRequest
     */
    body: NodeTagsRequest;
    headers?: {
        Accept?: string;
    };
    path: {
        /**
         * option to add or remove tags
         */
        action: string;
    };
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/nodes/tags/{action}';
};

export type PatchV1NodesTagsActionErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PatchV1NodesTagsActionError = PatchV1NodesTagsActionErrors[keyof PatchV1NodesTagsActionErrors];

export type PatchV1NodesTagsActionResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PatchV1NodesTagsActionResponse = PatchV1NodesTagsActionResponses[keyof PatchV1NodesTagsActionResponses];

export type GetV1NodesTokenInterfaceData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        /**
         * interface token will be created for
         */
        interface: string;
    };
    query?: {
        /**
         * Filter by nodeset. Minimum of one query parameter is required
         */
        nodeset?: string;
        /**
         * Filter by tags. Minimum of one query parameter is required
         */
        tags?: string;
    };
    url: '/v1/nodes/token/{interface}';
};

export type GetV1NodesTokenInterfaceErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1NodesTokenInterfaceError = GetV1NodesTokenInterfaceErrors[keyof GetV1NodesTokenInterfaceErrors];

export type GetV1NodesTokenInterfaceResponses = {
    /**
     * OK
     */
    200: NodeBootTokenResponse;
};

export type GetV1NodesTokenInterfaceResponse = GetV1NodesTokenInterfaceResponses[keyof GetV1NodesTokenInterfaceResponses];

export type GetV1RolesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by name
         */
        name?: string;
    };
    url: '/v1/roles';
};

export type GetV1RolesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1RolesError = GetV1RolesErrors[keyof GetV1RolesErrors];

export type GetV1RolesResponses = {
    /**
     * OK
     */
    200: GetRolesResponse;
};

export type GetV1RolesResponse = GetV1RolesResponses[keyof GetV1RolesResponses];

export type PatchV1RolesData = {
    /**
     * Request body for api.PatchRolesRequest
     */
    body: PatchRolesRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/roles';
};

export type PatchV1RolesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PatchV1RolesError = PatchV1RolesErrors[keyof PatchV1RolesErrors];

export type PatchV1RolesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PatchV1RolesResponse = PatchV1RolesResponses[keyof PatchV1RolesResponses];

export type PostV1RolesData = {
    /**
     * Request body for api.PostRolesRequest
     */
    body: PostRolesRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/roles';
};

export type PostV1RolesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1RolesError = PostV1RolesErrors[keyof PostV1RolesErrors];

export type PostV1RolesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PostV1RolesResponse = PostV1RolesResponses[keyof PostV1RolesResponses];

export type DeleteV1RolesNamesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        /**
         * Delete by name
         */
        names: string;
    };
    query?: never;
    url: '/v1/roles/{names}';
};

export type DeleteV1RolesNamesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1RolesNamesError = DeleteV1RolesNamesErrors[keyof DeleteV1RolesNamesErrors];

export type DeleteV1RolesNamesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type DeleteV1RolesNamesResponse = DeleteV1RolesNamesResponses[keyof DeleteV1RolesNamesResponses];

export type GetV1SwitchNodesetLldpData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        nodeset: string;
    };
    query?: {
        /**
         * Filter by port name
         */
        ports?: string;
    };
    url: '/v1/switch/{nodeset}/lldp';
};

export type GetV1SwitchNodesetLldpErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1SwitchNodesetLldpError = GetV1SwitchNodesetLldpErrors[keyof GetV1SwitchNodesetLldpErrors];

export type GetV1SwitchNodesetLldpResponses = {
    /**
     * OK
     */
    200: Array<Lldp>;
};

export type GetV1SwitchNodesetLldpResponse = GetV1SwitchNodesetLldpResponses[keyof GetV1SwitchNodesetLldpResponses];

export type GetV1UsersData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        /**
         * Filter by usernames
         */
        usernames?: string;
    };
    url: '/v1/users';
};

export type GetV1UsersErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type GetV1UsersError = GetV1UsersErrors[keyof GetV1UsersErrors];

export type GetV1UsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetV1UsersResponse = GetV1UsersResponses[keyof GetV1UsersResponses];

export type PostV1UsersData = {
    /**
     * Request body for api.UserStoreRequest
     */
    body: UserStoreRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type PostV1UsersErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PostV1UsersError = PostV1UsersErrors[keyof PostV1UsersErrors];

export type PostV1UsersResponses = {
    /**
     * OK
     */
    200: UserStoreResponse;
};

export type PostV1UsersResponse = PostV1UsersResponses[keyof PostV1UsersResponses];

export type DeleteV1UsersUsernamesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        /**
         * target usernames
         */
        usernames: string;
    };
    query?: never;
    url: '/v1/users/{usernames}';
};

export type DeleteV1UsersUsernamesErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type DeleteV1UsersUsernamesError = DeleteV1UsersUsernamesErrors[keyof DeleteV1UsersUsernamesErrors];

export type DeleteV1UsersUsernamesResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type DeleteV1UsersUsernamesResponse = DeleteV1UsersUsernamesResponses[keyof DeleteV1UsersUsernamesResponses];

export type PatchV1UsersUsernamesEnableData = {
    /**
     * Request body for api.UserEnableRequest
     */
    body: UserEnableRequest;
    headers?: {
        Accept?: string;
    };
    path: {
        /**
         * target usernames
         */
        usernames: string;
    };
    query?: never;
    url: '/v1/users/{usernames}/enable';
};

export type PatchV1UsersUsernamesEnableErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PatchV1UsersUsernamesEnableError = PatchV1UsersUsernamesEnableErrors[keyof PatchV1UsersUsernamesEnableErrors];

export type PatchV1UsersUsernamesEnableResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PatchV1UsersUsernamesEnableResponse = PatchV1UsersUsernamesEnableResponses[keyof PatchV1UsersUsernamesEnableResponses];

export type PatchV1UsersUsernamesRoleData = {
    /**
     * Request body for api.UserRoleRequest
     */
    body: UserRoleRequest;
    headers?: {
        Accept?: string;
    };
    path: {
        /**
         * target usernames
         */
        usernames: string;
    };
    query?: never;
    url: '/v1/users/{usernames}/role';
};

export type PatchV1UsersUsernamesRoleErrors = {
    /**
     * Default Error
     */
    default: HttpError;
};

export type PatchV1UsersUsernamesRoleError = PatchV1UsersUsernamesRoleErrors[keyof PatchV1UsersUsernamesRoleErrors];

export type PatchV1UsersUsernamesRoleResponses = {
    /**
     * OK
     */
    200: GenericResponse;
};

export type PatchV1UsersUsernamesRoleResponse = PatchV1UsersUsernamesRoleResponses[keyof PatchV1UsersUsernamesRoleResponses];
