// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { UseQueryResult } from "@tanstack/react-query";
import { hostDelete, hostFind, hostList, hostProvision, hostTag, hostTags, hostUnprovision, hostUntag, imageDelete, imageFind, imageList, restore, storeHosts, storeImages, userList } from "../requests/services.gen";
export type HostListDefaultResponse = Awaited<ReturnType<typeof hostList>>["data"];
export type HostListQueryResult<TData = HostListDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useHostListKey = "HostList";
export const UseHostListKeyFn = (clientOptions: Options<unknown, true> = {}, queryKey?: Array<unknown>) => [useHostListKey, ...(queryKey ?? [clientOptions])];
export type HostFindDefaultResponse = Awaited<ReturnType<typeof hostFind>>["data"];
export type HostFindQueryResult<TData = HostFindDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useHostFindKey = "HostFind";
export const UseHostFindKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useHostFindKey, ...(queryKey ?? [clientOptions])];
export type HostTagsDefaultResponse = Awaited<ReturnType<typeof hostTags>>["data"];
export type HostTagsQueryResult<TData = HostTagsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useHostTagsKey = "HostTags";
export const UseHostTagsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useHostTagsKey, ...(queryKey ?? [clientOptions])];
export type UserListDefaultResponse = Awaited<ReturnType<typeof userList>>["data"];
export type UserListQueryResult<TData = UserListDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useUserListKey = "UserList";
export const UseUserListKeyFn = (clientOptions: Options<unknown, true> = {}, queryKey?: Array<unknown>) => [useUserListKey, ...(queryKey ?? [clientOptions])];
export type ImageListDefaultResponse = Awaited<ReturnType<typeof imageList>>["data"];
export type ImageListQueryResult<TData = ImageListDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useImageListKey = "ImageList";
export const UseImageListKeyFn = (clientOptions: Options<unknown, true> = {}, queryKey?: Array<unknown>) => [useImageListKey, ...(queryKey ?? [clientOptions])];
export type ImageFindDefaultResponse = Awaited<ReturnType<typeof imageFind>>["data"];
export type ImageFindQueryResult<TData = ImageFindDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useImageFindKey = "ImageFind";
export const UseImageFindKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useImageFindKey, ...(queryKey ?? [clientOptions])];
export type StoreHostsMutationResult = Awaited<ReturnType<typeof storeHosts>>;
export const useStoreHostsKey = "StoreHosts";
export const UseStoreHostsKeyFn = (mutationKey?: Array<unknown>) => [useStoreHostsKey, ...(mutationKey ?? [])];
export type StoreImagesMutationResult = Awaited<ReturnType<typeof storeImages>>;
export const useStoreImagesKey = "StoreImages";
export const UseStoreImagesKeyFn = (mutationKey?: Array<unknown>) => [useStoreImagesKey, ...(mutationKey ?? [])];
export type RestoreMutationResult = Awaited<ReturnType<typeof restore>>;
export const useRestoreKey = "Restore";
export const UseRestoreKeyFn = (mutationKey?: Array<unknown>) => [useRestoreKey, ...(mutationKey ?? [])];
export type HostProvisionMutationResult = Awaited<ReturnType<typeof hostProvision>>;
export const useHostProvisionKey = "HostProvision";
export const UseHostProvisionKeyFn = (mutationKey?: Array<unknown>) => [useHostProvisionKey, ...(mutationKey ?? [])];
export type HostUnprovisionMutationResult = Awaited<ReturnType<typeof hostUnprovision>>;
export const useHostUnprovisionKey = "HostUnprovision";
export const UseHostUnprovisionKeyFn = (mutationKey?: Array<unknown>) => [useHostUnprovisionKey, ...(mutationKey ?? [])];
export type HostTagMutationResult = Awaited<ReturnType<typeof hostTag>>;
export const useHostTagKey = "HostTag";
export const UseHostTagKeyFn = (mutationKey?: Array<unknown>) => [useHostTagKey, ...(mutationKey ?? [])];
export type HostUntagMutationResult = Awaited<ReturnType<typeof hostUntag>>;
export const useHostUntagKey = "HostUntag";
export const UseHostUntagKeyFn = (mutationKey?: Array<unknown>) => [useHostUntagKey, ...(mutationKey ?? [])];
export type HostDeleteMutationResult = Awaited<ReturnType<typeof hostDelete>>;
export const useHostDeleteKey = "HostDelete";
export const UseHostDeleteKeyFn = (mutationKey?: Array<unknown>) => [useHostDeleteKey, ...(mutationKey ?? [])];
export type ImageDeleteMutationResult = Awaited<ReturnType<typeof imageDelete>>;
export const useImageDeleteKey = "ImageDelete";
export const UseImageDeleteKeyFn = (mutationKey?: Array<unknown>) => [useImageDeleteKey, ...(mutationKey ?? [])];
