// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { useMutation, UseMutationOptions, useQuery, UseQueryOptions } from "@tanstack/react-query";
import { hostDelete, hostFind, hostList, hostProvision, hostTag, hostTags, hostUnprovision, hostUntag, imageDelete, imageFind, imageList, restore, storeHosts, storeImages, userList } from "../requests/services.gen";
import { HostDeleteData, HostDeleteError, HostFindData, HostFindError, HostListError, HostProvisionData, HostProvisionError, HostTagData, HostTagError, HostTagsData, HostTagsError, HostUnprovisionData, HostUnprovisionError, HostUntagData, HostUntagError, ImageDeleteData, ImageDeleteError, ImageFindData, ImageFindError, ImageListError, RestoreData, RestoreError, StoreHostsData, StoreHostsError, StoreImagesData, StoreImagesError, UserListError } from "../requests/types.gen";
import * as Common from "./common";
export const useHostList = <TData = Common.HostListDefaultResponse, TError = HostListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseHostListKeyFn(clientOptions, queryKey), queryFn: () => hostList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useHostFind = <TData = Common.HostFindDefaultResponse, TError = HostFindError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<HostFindData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseHostFindKeyFn(clientOptions, queryKey), queryFn: () => hostFind({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useHostTags = <TData = Common.HostTagsDefaultResponse, TError = HostTagsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<HostTagsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseHostTagsKeyFn(clientOptions, queryKey), queryFn: () => hostTags({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useUserList = <TData = Common.UserListDefaultResponse, TError = UserListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseUserListKeyFn(clientOptions, queryKey), queryFn: () => userList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useImageList = <TData = Common.ImageListDefaultResponse, TError = ImageListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseImageListKeyFn(clientOptions, queryKey), queryFn: () => imageList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useImageFind = <TData = Common.ImageFindDefaultResponse, TError = ImageFindError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<ImageFindData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseImageFindKeyFn(clientOptions, queryKey), queryFn: () => imageFind({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useStoreHosts = <TData = Common.StoreHostsMutationResult, TError = StoreHostsError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<StoreHostsData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<StoreHostsData, true>, TContext>({ mutationKey: Common.UseStoreHostsKeyFn(mutationKey), mutationFn: clientOptions => storeHosts(clientOptions) as unknown as Promise<TData>, ...options });
export const useStoreImages = <TData = Common.StoreImagesMutationResult, TError = StoreImagesError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<StoreImagesData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<StoreImagesData, true>, TContext>({ mutationKey: Common.UseStoreImagesKeyFn(mutationKey), mutationFn: clientOptions => storeImages(clientOptions) as unknown as Promise<TData>, ...options });
export const useRestore = <TData = Common.RestoreMutationResult, TError = RestoreError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<RestoreData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<RestoreData, true>, TContext>({ mutationKey: Common.UseRestoreKeyFn(mutationKey), mutationFn: clientOptions => restore(clientOptions) as unknown as Promise<TData>, ...options });
export const useHostProvision = <TData = Common.HostProvisionMutationResult, TError = HostProvisionError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<HostProvisionData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<HostProvisionData, true>, TContext>({ mutationKey: Common.UseHostProvisionKeyFn(mutationKey), mutationFn: clientOptions => hostProvision(clientOptions) as unknown as Promise<TData>, ...options });
export const useHostUnprovision = <TData = Common.HostUnprovisionMutationResult, TError = HostUnprovisionError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<HostUnprovisionData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<HostUnprovisionData, true>, TContext>({ mutationKey: Common.UseHostUnprovisionKeyFn(mutationKey), mutationFn: clientOptions => hostUnprovision(clientOptions) as unknown as Promise<TData>, ...options });
export const useHostTag = <TData = Common.HostTagMutationResult, TError = HostTagError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<HostTagData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<HostTagData, true>, TContext>({ mutationKey: Common.UseHostTagKeyFn(mutationKey), mutationFn: clientOptions => hostTag(clientOptions) as unknown as Promise<TData>, ...options });
export const useHostUntag = <TData = Common.HostUntagMutationResult, TError = HostUntagError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<HostUntagData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<HostUntagData, true>, TContext>({ mutationKey: Common.UseHostUntagKeyFn(mutationKey), mutationFn: clientOptions => hostUntag(clientOptions) as unknown as Promise<TData>, ...options });
export const useHostDelete = <TData = Common.HostDeleteMutationResult, TError = HostDeleteError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<HostDeleteData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<HostDeleteData, true>, TContext>({ mutationKey: Common.UseHostDeleteKeyFn(mutationKey), mutationFn: clientOptions => hostDelete(clientOptions) as unknown as Promise<TData>, ...options });
export const useImageDelete = <TData = Common.ImageDeleteMutationResult, TError = ImageDeleteError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<ImageDeleteData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<ImageDeleteData, true>, TContext>({ mutationKey: Common.UseImageDeleteKeyFn(mutationKey), mutationFn: clientOptions => imageDelete(clientOptions) as unknown as Promise<TData>, ...options });
