// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { UseQueryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { hostFind, hostList, hostTags, imageFind, imageList, userList } from "../requests/services.gen";
import { HostFindData, HostFindError, HostListError, HostTagsData, HostTagsError, ImageFindData, ImageFindError, ImageListError, UserListError } from "../requests/types.gen";
import * as Common from "./common";
export const useHostListSuspense = <TData = Common.HostListDefaultResponse, TError = HostListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseHostListKeyFn(clientOptions, queryKey), queryFn: () => hostList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useHostFindSuspense = <TData = Common.HostFindDefaultResponse, TError = HostFindError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<HostFindData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseHostFindKeyFn(clientOptions, queryKey), queryFn: () => hostFind({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useHostTagsSuspense = <TData = Common.HostTagsDefaultResponse, TError = HostTagsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<HostTagsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseHostTagsKeyFn(clientOptions, queryKey), queryFn: () => hostTags({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useUserListSuspense = <TData = Common.UserListDefaultResponse, TError = UserListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseUserListKeyFn(clientOptions, queryKey), queryFn: () => userList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useImageListSuspense = <TData = Common.ImageListDefaultResponse, TError = ImageListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseImageListKeyFn(clientOptions, queryKey), queryFn: () => imageList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useImageFindSuspense = <TData = Common.ImageFindDefaultResponse, TError = ImageFindError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<ImageFindData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseImageFindKeyFn(clientOptions, queryKey), queryFn: () => imageFind({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
