/*
 * Grendel API
 *
 * Bare Metal Provisioning system for HPC Linux clusters. Find out more about Grendel at [https://github.com/ubccr/grendel](https://github.com/ubccr/grendel)
 *
 * API version: 1.0.0
 * Contact: aebruno2@buffalo.edu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ErrorResponse struct for ErrorResponse
type ErrorResponse struct {
	Message string `json:"message,omitempty"`
}
