generator:
  features:
    enable:
      # Enables paths client generation
      - "paths/client"
      # Enables paths server generation
      # - 'paths/server'
      # Enables webhooks client generation
      # - 'webhooks/client'
      # Enables webhooks server generation
      # - 'webhooks/server'
      # Enables client usage in security source implementations
      - "client/security/reentrant"
      # Enables validation of client requests
      - "client/request/validation"
      # Enables validation of server responses
      # - 'server/response/validation'
      # Enables OpenTelemetry integration
      # - 'ogen/otel'
      # Enables stub Handler generation
      - "ogen/unimplemented"
      # Enables example tests generation
      - "debug/example_tests"
    disable_all: true
  # ignore_not_implemented: ["unsupported content types"]
